### ISSUE TITLE
Upgrade docker compose.

### ISSUE THREAD

**Issue by stuaxo** [stuaxo/docker-compose-wp-duplicate#5]
Upgrade to a new version of docker-compose.

**Comment by blachawk** [comment]
When will this be updated to version 3.x?

**Comment by stuaxo** [comment]
I'm happy to except a PR.

**Comment by stuaxo** [comment]
Basically I only use this to really occasionally run my old WordPress site to grab a bit of data, so without a PR it probably won't happen until I next try and find out something broke.
