### ISSUE TITLE
where is the wp-archive folder?

### ISSUE THREAD

**Issue by blachawk** [stuaxo/docker-compose-wp-duplicate#7]
> Copy the duplicator archive and installer.php to the wp-archive folder.

Where is it?  When I clone down this project, there is no wp-archive folder.  Does it need to be created manually? If so, where do I stick it before I place my wp assets inside of it and do a docker-compose up?

**Comment by stuaxo** [comment]
Good catch - you do need to create it in project directory.
The add the backup zip into that folder.

When you run docker-compose up it handles extracting it and running it.

**Comment by blachawk** [comment]
Thanks for the tip!

**Comment by stuaxo** [comment]
If that worked I should probably add this info to the README.
